language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -f Dockerfile.dev -t sjssoon/docker-react-tutorial .

script:
 - docker run -e CI=true sjssoon/docker-react-tutorial npm run test
